config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :references
  resources :reviews
  resources :reservations
  root 'home#index'

  get '/signup', to: 'users#new', as: :signup
  get '/signin', to: 'sessions#new', as: :signin
  get '/signout', to: 'sessions#destroy', as: :signout

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tours

  scope path: '/', controller: :home do
    get 'peertours101', action: :about, as: :about
    get 'terms', action: :terms
    get 'privacy', action: :privacy
    get 'cancellation-policies', action: :cancellation_policies
    get 'help-for-travellers', action: :help_for_travellers
    get 'help-for-guides', action: :help_for_guides
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/message_thread.rb
class MessageThread < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/reference_request.rb
class ReferenceRequest < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :host, class_name: :User
  has_many :tour_rules, inverse_of: :tour, dependent: :destroy
  has_many :tour_flows, dependent: :destroy
  accepts_nested_attributes_for :tour_flows, allow_destroy: true, reject_if: :all_blank
  has_many :tour_categories, inverse_of: :tour, dependent: :destroy
  has_many :tour_prices, inverse_of: :tour, dependent: :destroy
  has_many :tour_photos, inverse_of: :tour, dependent: :destroy

  validates :name, length: { in: 10..100 }
  validates :outline, length: { in: 100.. 1000 }
  validates :description, length: { in: 100..5000 }
  validates :minimum_number, presence: true
  validates :maximum_number, presence: true
  validates :rendezvous, presence: true
end

app/models/tour_category.rb
class TourCategory < ActiveRecord::Base
  validates :tour, presence: true
  belongs_to :tour, inverse_of: :tour_categories
end

app/models/tour_flow.rb
class TourFlow < ActiveRecord::Base
  belongs_to :tour
end

app/models/tour_photo.rb
class TourPhoto < ActiveRecord::Base
  validates :tour, presence: true
  belongs_to :tour, inverse_of: :tour_photos
end

app/models/tour_price.rb
class TourPrice < ActiveRecord::Base
  validates :tour, presence: true
  belongs_to :tour, inverse_of: :tour_prices
end

app/models/tour_rule.rb
class TourRule < ActiveRecord::Base
  validates :tour, presence: true
  belongs_to :tour, inverse_of: :tour_rules
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 , maximum: 14}

  has_many :tours, foreign_key: :host_id, dependent: :destroy

  has_secure_password

  before_create :create_remember_token

  class << self
    def generate_remember_token
      SecureRandom.urlsafe_base64
    end

    def digest(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
  end

  private
  def create_remember_token
    self.remember_token = User.digest(User.generate_remember_token)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.generate_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

    def sign_out
      current_user.update_attribute(:remember_token,
        User.digest(User.generate_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "peertours"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "readable", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "readable"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= title
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield


    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    // = javascript_include_tag "readable"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/shared/_footer.html.haml
%footer#footer.footer-container
  .container-fluid
    .row
      .col-md-3
        %h2.hide-sm Company
        %ul
          %li 
            =link_to "PeerTours 101", about_path
          %li
            =link_to "Terms & Conditions", terms_path
          %li
            =link_to "Privacy Policy", privacy_path
      .col-md-3.hide-sm
        %h2 For Travellers
        %ul
          %li
            =link_to "Cancellation Policies", cancellation_policies_path
          %li
            =link_to "Help for Travellers", help_for_travellers_path
      .col-md-3.hide-sm
        %h2 For Guides
        %ul
          %li
            =link_to "よくある質問(ガイド向け)", help_for_guides_path
      .col-md-3.hide-sm
        %h2 Social
        %ul
          %li
            %a{href: "https://twitter.com/PeerTours"} Twitter
          %li
            %a{href: "https://www.facebook.com/pages/PeerTours/403372703179689"} Facebook
          %li
            %a{href: "https://instagram.com/peertours/"} Instagram
    %hr.footer-divider.row-space-top-8.row-space-4.hide-sm
    .text-center
      .row-space-top-2.text-muted © RisingAsia, Inc.

app/views/shared/_header.html.haml
.header-wrapper
  %header.regular-header.active
    %nav.navbar.navbar-default.header-nav
      .container-fluid
        .navbar-header
          %button{ class: "navbar-toggle toggle-custom", type: "button", id: "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#navbar"}
            %span.fa.fa-bars
          =link_to root_path do
            #logo{alt: "PeerTours Logo"}
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if signed_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = current_user.first_name
                  %b.caret.white-caret
                %ul.dropdown-menu
                  %li= link_to "Profile", current_user
                  %li.menu-divider
                  %li= link_to "Sign out", signout_path

            - else
              %li= link_to "Log In", signin_path
              %li= link_to "Sign Up", signup_path, class: "button red"